# Generated by Django 4.2.3 on 2024-01-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_boleta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='proveedor_transporte',
            field=models.CharField(blank=True, default='MusicPro', max_length=255, null=True),
        ),
    ]
